# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azctx < Formula
  desc "azctx is a command line tool whose aim is to ease the use of the official az cli. It is heavily inspired by kubectx.
"
  homepage "https://www.device-insight.com/"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/deviceinsight/azctx/releases/download/v0.0.2/azctx_0.0.2_Darwin_arm64.tar.gz"
      sha256 "92254d8ab50f0a4ec2d65746ffab034e473997464c19574ca87cab49f291aaec"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/azctx/releases/download/v0.0.2/azctx_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "ebf765690771853afa16bd92792a1e6d5cd96fe6443fb6ce27a6a815d7bfecdd"

      def install
        bin.install "azctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/azctx/releases/download/v0.0.2/azctx_0.0.2_Linux_x86_64.tar.gz"
      sha256 "7b2e0f7f5b7a706dd2444c50ebab8222298322802c9af77e11746da69bd1f235"

      def install
        bin.install "azctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deviceinsight/azctx/releases/download/v0.0.2/azctx_0.0.2_Linux_arm64.tar.gz"
      sha256 "5ac2e83e08357169106c5b2a880adc42ca3d76671ebca24a71bca8412916501c"

      def install
        bin.install "azctx"
      end
    end
  end
end
