# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkactlAzurePlugin < Formula
  desc "Azure Plugin for kafkactl"
  homepage "https://www.device-insight.com/"
  version "1.0.4"

  depends_on "kafkactl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_darwin_amd64.tar.gz"
      sha256 "cc0cf3dd82429e56eed6b0b8c7d514bdbd24384e9179913fc993a1366ef53c8d"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_darwin_arm64.tar.gz"
      sha256 "843535f1ffada5ab246a14c7167b840b9da18d9c23d04fd04001b098d2e2dbdb"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_linux_arm64.tar.gz"
      sha256 "2538c7b8ca235c87537b7a123bfe9b2e073fa7d0f472eec4e61615c534315c11"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_linux_amd64.tar.gz"
      sha256 "16c3d350c3caf8413bb1aa70bb8b934936a630f8174183fefc268b6b3912227e"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
  end
end
