# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkactl < Formula
  desc "A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
In addition kafkactl supports auto-completion for its commands as well as topic names.
"
  homepage "https://www.device-insight.com/"
  version "1.15.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/deviceinsight/kafkactl/releases/download/v1.15.1/kafkactl_1.15.1_Darwin_x86_64.tar.gz"
    sha256 "7621d9f625eebd1bebbf3072478889b15389e972cf83d57c9ab23d7ca5d4621b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/deviceinsight/kafkactl/releases/download/v1.15.1/kafkactl_1.15.1_Linux_x86_64.tar.gz"
    sha256 "f4c10ebca8ddbec9f5db39c6fec607af36ef68e3eff426e1fea18b7402557382"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/deviceinsight/kafkactl/releases/download/v1.15.1/kafkactl_1.15.1_Linux_arm64.tar.gz"
    sha256 "66e754851940a703c578961845401315b63acce50597f46366e64bd324084e31"
  end

  def install
    bin.install "kafkactl"
  end
end
