# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkactlAzurePlugin < Formula
  desc "Azure Plugin for kafkactl"
  homepage "https://www.device-insight.com/"
  version "1.3.0"

  depends_on "kafkactl"

  on_macos do
    on_intel do
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.3.0/kafkactl-azure-plugin_1.3.0_darwin_amd64.tar.gz"
      sha256 "06c1f7acfcb67966f2eb7f6288e9b1ee740313d14937e4f9b5fcc1ce1f6461e1"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
    on_arm do
      url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.3.0/kafkactl-azure-plugin_1.3.0_darwin_arm64.tar.gz"
      sha256 "84bf867f5daf5b00cf90fe7f3852ccc7ec7c759ec1dc35539b28a23d47d7db46"

      def install
        bin.install "kafkactl-azure-plugin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.3.0/kafkactl-azure-plugin_1.3.0_linux_amd64.tar.gz"
        sha256 "40ff54cfec17dfa50f1ea12db1055a3e26a2e26e338f4e5c0c421c2f1093865b"

        def install
          bin.install "kafkactl-azure-plugin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.3.0/kafkactl-azure-plugin_1.3.0_linux_arm64.tar.gz"
        sha256 "76e6c25832ffc9e28a61d40b6f2a9d2abffd768dcd740c55cd280c440deb0d68"

        def install
          bin.install "kafkactl-azure-plugin"
        end
      end
    end
  end
end
