# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafkactl < Formula
  desc "A Commandline interface for Apache Kafka which provides useful features adapted from kubectl for Kubernetes.
Multiple kafka brokers can be configured in a config file and the active broker is also persisted within the config.
In addition kafkactl supports auto-completion for its commands as well as topic names.
"
  homepage "https://www.device-insight.com/"
  version "1.24.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/deviceinsight/kafkactl/releases/download/v1.24.0/kafkactl_1.24.0_darwin_arm64.tar.gz"
      sha256 "45123e06d4f6ee3d11dd3f90a07ada19fd34cfc81b801cbaf9e2b5e306dfe8dd"

      def install
        bin.install "kafkactl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/kafkactl/releases/download/v1.24.0/kafkactl_1.24.0_darwin_amd64.tar.gz"
      sha256 "19473228c6cfd96f4e38e14221aa9883a0f2a39b849e9def567d361c28153096"

      def install
        bin.install "kafkactl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deviceinsight/kafkactl/releases/download/v1.24.0/kafkactl_1.24.0_linux_arm64.tar.gz"
      sha256 "bd5d7a07e4ed8ad584d666a2420816b38919e3db3393a681b278691cfb2fdc7d"

      def install
        bin.install "kafkactl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deviceinsight/kafkactl/releases/download/v1.24.0/kafkactl_1.24.0_linux_amd64.tar.gz"
      sha256 "876da25725aadfcfb5b7631271a0ecdfc6506ab609792119c3c7582a4340358e"

      def install
        bin.install "kafkactl"
      end
    end
  end
end
